Create roles & Set Permissions.
atlp-rwanda/phantom-fe-techode pull request #19
Opened 2022-03-03 07:26 UTC by jeandamascyifuzo

**What this pr does**
Dashboard design for admin to Create roles & Set Permissions.

**How you may test it**
Clone this repo if you did not
Change to ft-rolesAndSetPermissions-TP-32
Run npm install to get dependence
Run npm run dev to run the server
Navigate to the /emovePermission
For removing permision
click the permisionName
then remove button
Related trello board
[Create roles & Set Permissions ](https://trello.com/c/45AD2G2a/32-create-roles-set-permissions)

Screenshoots
![Screenshot from 2022-03-03 02-22-44](https://user-images.githubusercontent.com/87600918/156516382-59d0279e-16c0-4a77-ba0f-8c5136cf5f9b.png)

![Screenshot from 2022-03-03 02-22-48](https://user-images.githubusercontent.com/87600918/156516619-df07c93b-e5f9-486f-b04b-4765a75deef7.png)

2022-03-07 09:14 UTC, renepromesse requested changes
Good work @jeandamascyifuzo, improve these feedback:

- when I click on `Get routes` the popup mention `Get bus` Permission, try to make it accurate

![image](https://user-images.githubusercontent.com/69194903/157001276-4fa999c4-4db8-4b06-ad6e-2e96b007846d.png)
![image](https://user-images.githubusercontent.com/69194903/157001334-2d718729-f956-4175-a963-172d795f37b0.png)

- please update the state so that when one permission is remove, the UI will show only 2 permission and so on...
- on the buttons for mobile, the text is not correctly centered, please use flex to center it horizontally  
![image](https://user-images.githubusercontent.com/69194903/157001833-a3e5c1ac-ae1e-4905-8739-919a9bfae33f.png)

2022-03-07 09:18 UTC, renepromesse requested changes

2022-03-07 09:18 UTC, renepromesse commented on src/App.js
> +                <Route path="/removePermission" exact component={RemovePermission} />
the route should be renamed from /removePermission to /roles

2022-03-08 10:04 UTC, chanceDira approved these changes

2022-03-10 04:46 UTC, sezeranoJchrisostome reviewed
Let's close this pr since we have all this features

2022-03-10 06:13 UTC, closed without merging