#TP-12 ft:Reset password
atlp-rwanda/phantom-fe-techode pull request #33
Opened 2022-04-27 13:53 UTC by jeandamascyifuzo

### What this PR does
This Pr allows the driver or operator to reset their password.

 
- [x] **driver** and **operator** are able to provide their email.
- [x] Email containing a reset password link is sent to their email
- [x] **driver** and **operator** will be able to reset their password.
- [x] Appropriate error messages are displayed on unsuccessful attempts

Trello card Id

> #TP-12

 ### How you can manually test it

1. Clone the repo
2. checkout to ft-resetPass-integration-TP-12 branch
3. git pull origin ft-resetPass-integration-TP-12
4.  add this URL: BASE_URL=http://localhost:8080/newpassword/accounts/reset-password/   .env=>backend

**Install all dependencies using** 
`npm i`

**run development server using**
`npm run dev`

### TrelloCard

[link](https://trello.com/c/rgnoEv0m/12-reset-password)

**ScreenShot**
 ### unsuccessful attempts
<img width="1440" alt="Screen Shot 2022-04-28 at 16 37 57" src="https://user-images.githubusercontent.com/87600918/165778852-9caaa696-e4eb-4a93-b898-415be8e256b3.png">

 ### successful attempts
<img width="1440" alt="Screen Shot 2022-04-28 at 16 38 25" src="https://user-images.githubusercontent.com/87600918/165778984-18774d3d-ec1b-4e8b-8452-022a542c2b65.png">

2022-04-28 15:43 UTC, chanceDira submitted a review, later dismissed
**This really works fine 👍**

2022-04-29 06:44 UTC, renepromesse approved these changes

2022-04-29 07:02 UTC, sezeranoJchrisostome requested changes
Well done, @jeandamascyifuzo

2022-04-29 07:02 UTC, sezeranoJchrisostome commented on src/components/passwordReset/passwordereset.js
> +                                                className=" flex justify-center w-60 bg-sky-50 w-full appearance-none rounded  py-2 px-3 mb-3 text-xs font-semibold text-gray-900 leading-tight "
Can you reset this input and disable it when it is still in progress

2022-04-29 07:04 UTC, sezeranoJchrisostome commented on src/components/passwordReset/passwordereset.js
> +                                                className=" flex justify-center w-60 bg-sky-50 w-full appearance-none rounded  py-2 px-3 mb-3 text-xs font-semibold text-gray-900 leading-tight "
and also add notify

2022-04-29 07:12 UTC, sezeranoJchrisostome requested changes

2022-04-29 07:12 UTC, sezeranoJchrisostome commented on src/components/passwordReset/passwordereset.js
> +            const { email } = values;
Can you call notify() here to show me that my request is being progressed?

2022-04-29 08:30 UTC, sezeranoJchrisostome approved these changes

2022-04-29 08:39 UTC, merged