Ft(integration) crud operation buses
atlp-rwanda/phantom-fe-techode pull request #41
Opened 2022-05-05 12:46 UTC by wakaflorien

### What this PR does?
This pr give an operator to perform CRUD operations for buses.

### Description of Task to be completed
 

- [ ] Appropriate error messages are displayed on unsuccessful attempt 
Notifies an operator to login first before creating a bus.

### How you may test it
Clone this repo if you did not already, if you did clone it run git fetch to get all repo
Run `git checkout` **ft-crud-operation-buses**
You may be required to pull again. run this too git pull origin **ft-crud-operation-buses**
Run `npm install
`Run `npm run dev`

open this [Link](http://localhost:8080/) in the browser
[![Run in Postman](https://run.pstmn.io/button.svg)](https://app.getpostman.com/run-collection/d11bd9b77a2e07caefff?action=collection%2Fimport)

Related Trello board story
[[Here](https://trello.com/c/PS9ndwXo/16-sign-in-to-phantom)](https://trello.com/c/PH02TBoY)

2022-05-05 19:27 UTC, renepromesse requested changes
Great work @wakaflorien , please fix the tests are failing and add the screenshots

2022-05-05 20:28 UTC, wakaflorien commented
> 

on it.

2022-05-06 05:06 UTC, chanceDira approved these changes
Nice work @wakaflorien

2022-05-06 06:12 UTC, renepromesse approved these changes

2022-05-06 06:13 UTC, merged