ft-signin form with validation-TP-29
atlp-rwanda/phantom-fe-techode pull request #9
Opened 2022-02-25 06:42 UTC by jeandamascyifuzo

**What this PR does**
This PR is for SignIn into Phantom with a valid email and password

**How you can test it**
git clone you will have to clone this repo if you have not already
git checkout **ft-signin-to-phantom-TP-29** change the branch
npm install for some new plugins installed for it to run
npm run dev you can use this script to run it locally on dev server
in the browser and **/login** to get login form
you can not login with any other email or password except **email: admin@andela.com pass: test123** and you will redirected to blackPage

**Related [Trello]**(https://trello.com/c/xsOcHsiV/8-setting-up-css-tailwind) card
Trello

**screen-shoot**
![Screenshot from 2022-02-25 01-37-55](https://user-images.githubusercontent.com/87600918/155666967-6654d926-6649-45b8-8e67-080eed3c6588.png)

2022-02-26 11:05 UTC, sezeranoJchrisostome submitted a review, later dismissed

2022-02-26 19:04 UTC, wakaflorien submitted a review, later dismissed

2022-02-27 13:42 UTC, chanceDira approved these changes

2022-02-28 10:53 UTC, sezeranoJchrisostome commented on src/components/signIn/LoginForm.js
> +                                        "bg-blue-500 hover:bg-blue-500 text-white font-bold py-2 px-4 rounded lg:ml-16 md:ml-6 lg:w-3/4 w-full"
Replace bg-blue-500 to bg-primary-500 or any pallet from 100 - 600 accordingly

2022-03-01 05:42 UTC, renepromesse requested changes
Please @jeandamascyifuzo , make sure your page looks like the design.
- no header
- no scrolling
- fix alignment issues, ( make the form centered)
- fix empty spaces

![2022-03-0107-37-04](https://user-images.githubusercontent.com/69194903/156111686-84d87262-a454-4cf9-80ba-29bb3c12765b.png)

2022-03-01 05:42 UTC, renepromesse commented on src/assets/style/LoginForm.css
> +    color: #1CA0E3;
please work together with @sezeranoJchrisostome , to fix his PR as soon as possible and then bring the colors he difined into yours. Apply all colors where you have colors

2022-03-02 04:37 UTC, chanceDira submitted a review, later dismissed

2022-03-25 09:36 UTC, mukunzidd commented
@jeandamascyifuzo 
- Rebase the current changes
- Add the correct Trello Link
- Fix the login functionality by actually protecting routes that need protecting

2022-04-25 10:56 UTC, renepromesse requested changes
Good job @jeandamascyifuzo , please attend the following reviews:
- squash all the 65 commits into 1

2022-04-25 10:56 UTC, renepromesse commented on src/functions/RanderMyLocation.js
>          //     "lng": bbox[2]
remove this commented lines

2022-04-26 12:06 UTC, merged